import numpy as np
from scipy.spatial import distance
from matplotlib import pyplot as plt

#list1 is the list of xyz for one organelle;list2 is the list of xyz for another organelle, generated by model2point command

list1 = np.genfromtxt('list1.csv')
list2 = np.genfromtxt('list2.csv')

#s1 = np.array([(0,0), (0,1), (1,0), (1,1)])
#s2 = np.array([(3,2), (1,9)])

dist=distance.cdist(list1,list2).min(axis=1)

#dist are value in pixel, need to multiply by the pixel size in nm

result=[x*1.35-4 for x in dist]
np.savetxt('result.txt', result, delimiter=',')

#import numpy as np
#import random
#from matplotlib import pyplot as plt

#data = np.random.normal(0, 20, 1000)
data=np.genfromtxt('result.txt')

# fixed bin size
bins = np.arange(min(data), max(data), 1) # fixed bin size

plt.xlim([min(data)-5, max(data)+5])

plt.hist(data, bins=bins, alpha=0.5, density=True)
plt.title('Intermembrane space')
plt.xlabel('Distance in nanometer')
plt.ylabel('Percentage')

plt.show()

